Bonus flow rate based on Quorum (#68)
* sum total active vote weight when voting

* add totalTokenSupplyVoteWeight

* basic test of totaltokensupplyvoteweight

* add nouns totalTokenSupplyVoteWeight

* add bonus flow rate based on quorum

* fix mock erc721, add dynamic bonus pool tests, reset flow rate when new votes happen and quorum % changes

* Update storage-check.sh

* update storage layout

* fix to use real rpc urls

* Update Flow.sol

* simplify

* Update Flow.sol

* Update Flow.sol

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -38,6 +38,11 @@ jobs:
             echo "Error: RPC_BASE environment variable is not set"
             exit 1
           fi
+          echo "RPC_MAINNET=${{ secrets.RPC_MAINNET }}" >> $GITHUB_ENV
+          if [ -z "${{ secrets.RPC_MAINNET }}" ]; then
+            echo "Error: RPC_MAINNET environment variable is not set"
+            exit 1
+          fi
 
       - name: Run Forge build
         run: |
