storage layout checks (#66)
* storage layout checks

* fix

* try dis

* minor fix

* Update test.yml

* try to add secret

* Update storage-check.sh

* Update test.yml

* update new storage layout

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -2,6 +2,8 @@ name: CI
 
 on:
   push:
+    branches:
+      - main
   pull_request:
   workflow_dispatch:
 
@@ -29,6 +31,14 @@ jobs:
         run: |
           forge --version
 
+      - name: Set environment variables
+        run: |
+          echo "RPC_BASE=${{ secrets.RPC_BASE }}" >> $GITHUB_ENV
+          if [ -z "${{ secrets.RPC_BASE }}" ]; then
+            echo "Error: RPC_BASE environment variable is not set"
+            exit 1
+          fi
+
       - name: Run Forge build
         run: |
           forge build --sizes
@@ -38,3 +48,8 @@ jobs:
         run: |
           forge test -vvv
         id: test
+
+      - name: Run Storage Inspection Test
+        run: |
+          cd ${{ github.workspace }} && ./script/storage-check.sh check @contracts.txt
+        id: storage-inspection
